### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by frspin** [cjcliffe/CubicSDR#503]
After recent update from git Gradient.cpp don't compile on my Ubuntu 16.04/64 bit
Changing size_t with std::size_t solve the problem

Regards

Franco Spinelli
IW2DHW

**Comment by vsonnier** [comment]
@frspin It should be fine this time, or so I hope.

**Comment by frspin** [comment]
Il 29/01/2017 21:31, Vincent Sonnier ha scritto:
> @frspin <https://github.com/frspin> It should be fine this time, or so I
> hope.
> 
> —

Yes. Compile and run without problems

Thanks

Franco Spinelli
IW2DHW
