### ISSUE TITLE
Compilation error on Ubuntu 14.04

### ISSUE THREAD

**Issue by frspin** [cjcliffe/CubicSDR#277]
CubicSDR updated today from Github don't compile on Ubuntu 14.04, with g++ 4.8.4
This is error message:

[ 10%] Building CXX object CMakeFiles/CubicSDR.dir/src/sdr/SDRDeviceInfo.cpp.o
In file included from /home/spin/Scaricati/ham/CubicSDR/src/sdr/SDRDeviceInfo.cpp:1:0:
/home/spin/Scaricati/ham/CubicSDR/src/sdr/SDRDeviceInfo.h:92:5: error: ‘atomic_bool’ in namespace ‘std’ does not name a type
     std::atomic_bool active;
     ^
/home/spin/Scaricati/ham/CubicSDR/src/sdr/SDRDeviceInfo.cpp: In constructor ‘SDRDeviceInfo::SDRDeviceInfo()’:
/home/spin/Scaricati/ham/CubicSDR/src/sdr/SDRDeviceInfo.cpp:4:104: error: class ‘SDRDeviceInfo’ does not have any field named ‘active’
 SDRDeviceInfo::SDRDeviceInfo() : name(""), serial(""), available(false), remote(false), manual(false), active(false), soapyDevice(nullptr) {
                                                                                                        ^
/home/spin/Scaricati/ham/CubicSDR/src/sdr/SDRDeviceInfo.cpp: In member function ‘bool SDRDeviceInfo::isActive() const’:
/home/spin/Scaricati/ham/CubicSDR/src/sdr/SDRDeviceInfo.cpp:41:12: error: ‘active’ was not declared in this scope
     return active.load();
            ^
/home/spin/Scaricati/ham/CubicSDR/src/sdr/SDRDeviceInfo.cpp: In member function ‘void SDRDeviceInfo::setActive(bool)’:
/home/spin/Scaricati/ham/CubicSDR/src/sdr/SDRDeviceInfo.cpp:45:11: error: ‘class SDRDeviceInfo’ has no member named ‘active’
     this->active.store(active);
           ^
/home/spin/Scaricati/ham/CubicSDR/src/sdr/SDRDeviceInfo.cpp: In member function ‘bool SDRDeviceInfo::hasCORR(int, size_t)’:
/home/spin/Scaricati/ham/CubicSDR/src/sdr/SDRDeviceInfo.cpp:170:53: error: no matching function for call to ‘find(std::vector<std::basic_string<char> >::iterator, std::vector<std::basic_string<char> >::iterator, const char [5])’
     if (std::find(freqs.begin(), freqs.end(), "CORR") != freqs.end()) {
                                                     ^
/home/spin/Scaricati/ham/CubicSDR/src/sdr/SDRDeviceInfo.cpp:170:53: note: candidate is:
In file included from /usr/include/c++/4.8/bits/locale_facets.h:48:0,
                 from /usr/include/c++/4.8/bits/basic_ios.h:37,
                 from /usr/include/c++/4.8/ios:44,
                 from /usr/include/c++/4.8/istream:38,
                 from /usr/include/c++/4.8/sstream:38,
                 from /usr/include/c++/4.8/complex:45,
                 from /usr/local/include/SoapySDR/Device.hpp:18,
                 from /home/spin/Scaricati/ham/CubicSDR/src/sdr/SDRDeviceInfo.h:7,
                 from /home/spin/Scaricati/ham/CubicSDR/src/sdr/SDRDeviceInfo.cpp:1:
/usr/include/c++/4.8/bits/streambuf_iterator.h:369:5: note: template<class _CharT2> typename __gnu_cxx::__enable_if<std::__is_char<_CharT2>::__value, std::istreambuf_iterator<_CharT> >::__type std::find(std::istreambuf_iterator<_CharT>, std::istreambuf_iterator<_CharT>, const _CharT2&)
     find(istreambuf_iterator<_CharT> __first,
     ^
/usr/include/c++/4.8/bits/streambuf_iterator.h:369:5: note:   template argument deduction/substitution failed:
/home/spin/Scaricati/ham/CubicSDR/src/sdr/SDRDeviceInfo.cpp:170:53: note:   ‘__gnu_cxx::__normal_iterator<std::basic_string<char>*, std::vector<std::basic_string<char> > >’ is not derived from ‘std::istreambuf_iterator<_CharT>’
     if (std::find(freqs.begin(), freqs.end(), "CORR") != freqs.end()) {
                                                     ^
/home/spin/Scaricati/ham/CubicSDR/src/sdr/SDRDeviceInfo.cpp: In member function ‘bool SDRDeviceInfo::isActive() const’:
/home/spin/Scaricati/ham/CubicSDR/src/sdr/SDRDeviceInfo.cpp:42:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
/home/spin/Scaricati/ham/CubicSDR/src/sdr/SDRDeviceInfo.cpp: In member function ‘bool SDRDeviceInfo::hasCORR(int, size_t)’:
/home/spin/Scaricati/ham/CubicSDR/src/sdr/SDRDeviceInfo.cpp:175:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
make[2]: *** [CMakeFiles/CubicSDR.dir/src/sdr/SDRDeviceInfo.cpp.o] Errore 1
make[1]: *** [CMakeFiles/CubicSDR.dir/all] Errore 2
make: *** [all] Errore 2

Regards
Franco Spinelli
IW2DHW

**Comment by cjcliffe** [comment]
Should be all fixed up now in master.
