### PR TITLE
fix build with wxWidgets 3.1.3

### PR DESCRIPTION
**Pull request by ra1nb0w**
AppFrame.cpp use wxToolTip() without including the library

### CODE REVIEW

**Comment by ra1nb0w** [comment]
thank you!

**Comment by vsonnier** [comment]
@ra1nb0w You are welcome, Thank you for your fix ! Compiles and run ok on my side for Win32 / Win64.

**Comment by emrecio** [comment]
Hi, seems to be having same error with wxWidgets Version     : 3.1.5; Release     : 150400.1.7

/home/erecio/elDrive/RTL/CubicSDR-0.2.4/src/AppFrame.cpp: In member function ‘void AppFrame::setStatusText(wxWindow*, std::__cxx11::string)’:
/home/erecio/elDrive/RTL/CubicSDR-0.2.4/src/AppFrame.cpp:3063:24: error: incomplete type ‘wxToolTip’ used in nested name specifier
wxToolTip::Enable(false);
^~~~~~
/home/erecio/elDrive/RTL/CubicSDR-0.2.4/src/AppFrame.cpp:3066:24: error: incomplete type ‘wxToolTip’ used in nested name specifier
wxToolTip::SetDelay(1000);
^~~~~~~~
/home/erecio/elDrive/RTL/CubicSDR-0.2.4/src/AppFrame.cpp:3067:24: error: incomplete type ‘wxToolTip’ used in nested name specifier
wxToolTip::Enable(true);
^~~~~~
make[2]: *** [CMakeFiles/CubicSDR.dir/build.make:104: CMakeFiles/CubicSDR.dir/src/AppFrame.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:110: CMakeFiles/CubicSDR.dir/all] Error 2
