### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by frspin** [cjcliffe/CubicSDR#261]
Current GIT version don't compile with Ubuntu 14.04 and c++ 4.8 (standard compiler for this Ubuntu version).

/home/spin/Scaricati/ham/CubicSDR/src/sdr/SDREnumerator.cpp: In static member function ‘static void SDREnumerator::removeManual(std::string, std::string)’:
/home/spin/Scaricati/ham/CubicSDR/src/sdr/SDREnumerator.cpp:424:28: error: no matching function for call to ‘std::vector<_SDRManualDef>::erase(std::vector<_SDRManualDef>::const_iterator&)’
             manuals.erase(i);

No problem compiling it with Ubuntu 15.10

Franco Spinelli
IW2DHW

**Comment by cjcliffe** [comment]
strange probably a GCC difference -- I have a ubuntu 14 VM here I'll take a look

**Comment by frspin** [comment]
Il 23/01/2016 16:51, Charles J. Cliffe ha scritto:
> strange probably a GCC difference -- I have a ubuntu 14 VM here I'll
> take a look

Ubuntu 14.04 have GCC 4.8.2 and Ubuntu 15.10 have 5.2.1

Franco Spinelli
IW2DHW

**Comment by zonduino** [comment]
I have the same error on openSUSE Leap 42.1 with c++ 4.8 and GCC 4.8.5
All previous builds were successful. 

Timothy Baker

**Comment by ryanniehaus** [comment]
Same here linux mint 17.3 gcc 4.8.4-2

**Comment by sm0yyq** [comment]
I have same trouble with v0.1.22-alpha and ubuntu 14.04, .. version 0.1.20-alpha compiles well.
It also throw out lots of warnings under compile time, on both versions.

**Comment by cjcliffe** [comment]
Should be fixed up now; had a typo that OSX and Windows don't seem to care about :)

**Comment by frspin** [comment]
Il 24/01/2016 16:20, Charles J. Cliffe ha scritto:
> Should be fixed up now; had a typo that OSX and Windows don't seem to
> care about :)
> 

I can confirm: the problem is solved on Ubuntu 14.04

Franco Spinelli
IW2DHW

**Comment by cjcliffe** [comment]
@frspin great; thanks for the quick response!
