### PR TITLE
AppFrame refactoring

### PR DESCRIPTION
**Pull request by cjcliffe**
Making AppFrame easier to work with:
- Break up large init/action/handlers into separate functions
- Move Session management code into it's own manager
- Minor renaming and cleanup
- Header file cleanup

### CODE REVIEW

**Comment by ra1nb0w** [comment]
I don't want to damage the party but on macOS 10.{11,12} I receive the following error on building

```make
/usr/bin/clang++  -DCUBICSDR_BUILD_TITLE="\"CubicSDR v0.2.5 :: www.cubicsdr.com\"" -DCUBICSDR_ENABLE_ABOUT_DIALOG=1 -DCUBICSDR_ENABLE_VIEW_DEMOD=1 -DCUBICSDR_ENABLE_VIEW_SCOPE=1 -DCUBICSDR_INSTALL_NAME=\"CubicSDR\" -DCUBICSDR_VERSION=\"0.2.5\" -DHAVE_TYPE_TRAITS=1 -DUSE_SOAPY_SDR=1 -DWXUSINGDLL -D_FILE_OFFSET_BITS=64 -D_OSX_APP_ -D__MACOSX_CORE__ -D__WXMAC__ -D__WXOSX_COCOA__ -D__WXOSX__ -I/opt/local/var/macports/build/_Users_travis_build_macports_macports-ports_science_CubicSDR/CubicSDR/work/CubicSDR-a000446610482299db079a1216774ed05d764165/external/rtaudio -I/opt/local/var/macports/build/_Users_travis_build_macports_macports-ports_science_CubicSDR/CubicSDR/work/CubicSDR-a000446610482299db079a1216774ed05d764165/src/forms/SDRDevices -I/opt/local/var/macports/build/_Users_travis_build_macports_macports-ports_science_CubicSDR/CubicSDR/work/CubicSDR-a000446610482299db079a1216774ed05d764165/src/forms/DigitalConsole -I/opt/local/var/macports/build/_Users_travis_build_macports_macports-ports_science_CubicSDR/CubicSDR/work/CubicSDR-a000446610482299db079a1216774ed05d764165/src/forms/Bookmark -I/opt/local/var/macports/build/_Users_travis_build_macports_macports-ports_science_CubicSDR/CubicSDR/work/CubicSDR-a000446610482299db079a1216774ed05d764165/src/forms/Dialog -I/opt/local/var/macports/build/_Users_travis_build_macports_macports-ports_science_CubicSDR/CubicSDR/work/CubicSDR-a000446610482299db079a1216774ed05d764165/src/sdr -I/opt/local/var/macports/build/_Users_travis_build_macports_macports-ports_science_CubicSDR/CubicSDR/work/CubicSDR-a000446610482299db079a1216774ed05d764165/src/demod -I/opt/local/var/macports/build/_Users_travis_build_macports_macports-ports_science_CubicSDR/CubicSDR/work/CubicSDR-a000446610482299db079a1216774ed05d764165/src/modules -I/opt/local/var/macports/build/_Users_travis_build_macports_macports-ports_science_CubicSDR/CubicSDR/work/CubicSDR-a000446610482299db079a1216774ed05d764165/src/modules/modem -I/opt/local/var/macports/build/_Users_travis_build_macports_macports-ports_science_CubicSDR/CubicSDR/work/CubicSDR-a000446610482299db079a1216774ed05d764165/src/modules/modem/digital -I/opt/local/var/macports/build/_Users_travis_build_macports_macports-ports_science_CubicSDR/CubicSDR/work/CubicSDR-a000446610482299db079a1216774ed05d764165/src/modules/modem/analog -I/opt/local/var/macports/build/_Users_travis_build_macports_macports-ports_science_CubicSDR/CubicSDR/work/CubicSDR-a000446610482299db079a1216774ed05d764165/src/audio -I/opt/local/var/macports/build/_Users_travis_build_macports_macports-ports_science_CubicSDR/CubicSDR/work/CubicSDR-a000446610482299db079a1216774ed05d764165/src/util -I/opt/local/var/macports/build/_Users_travis_build_macports_macports-ports_science_CubicSDR/CubicSDR/work/CubicSDR-a000446610482299db079a1216774ed05d764165/src/panel -I/opt/local/var/macports/build/_Users_travis_build_macports_macports-ports_science_CubicSDR/CubicSDR/work/CubicSDR-a000446610482299db079a1216774ed05d764165/src/visual -I/opt/local/var/macports/build/_Users_travis_build_macports_macports-ports_science_CubicSDR/CubicSDR/work/CubicSDR-a000446610482299db079a1216774ed05d764165/src/process -I/opt/local/var/macports/build/_Users_travis_build_macports_macports-ports_science_CubicSDR/CubicSDR/work/CubicSDR-a000446610482299db079a1216774ed05d764165/src/ui -I/opt/local/var/macports/build/_Users_travis_build_macports_macports-ports_science_CubicSDR/CubicSDR/work/CubicSDR-a000446610482299db079a1216774ed05d764165/src/rig -I/opt/local/var/macports/build/_Users_travis_build_macports_macports-ports_science_CubicSDR/CubicSDR/work/CubicSDR-a000446610482299db079a1216774ed05d764165/src -I/opt/local/var/macports/build/_Users_travis_build_macports_macports-ports_science_CubicSDR/CubicSDR/work/CubicSDR-a000446610482299db079a1216774ed05d764165/external/lodepng -I/opt/local/var/macports/build/_Users_travis_build_macports_macports-ports_science_CubicSDR/CubicSDR/work/CubicSDR-a000446610482299db079a1216774ed05d764165/external/tinyxml -I/opt/local/var/macports/build/_Users_travis_build_macports_macports-ports_science_CubicSDR/CubicSDR/work/CubicSDR-a000446610482299db079a1216774ed05d764165/external/cubicvr2/math -isystem /opt/local/Library/Frameworks/wxWidgets.framework/Versions/wxWidgets/3.1/lib/wx/include/osx_cocoa-unicode-3.1 -isystem /opt/local/Library/Frameworks/wxWidgets.framework/Versions/wxWidgets/3.1/include/wx-3.1  -pipe -Os -DNDEBUG -I/opt/local/include -stdlib=libc++ -O3 -DNDEBUG -arch x86_64 -mmacosx-version-min=10.12   -std=c++0x -pthread -mmacosx-version-min=10.9 -std=c++0x -pthread -std=gnu++11 -o CMakeFiles/CubicSDR.dir/src/sdr/SDRDeviceInfo.cpp.o -c /opt/local/var/macports/build/_Users_travis_build_macports_macports-ports_science_CubicSDR/CubicSDR/work/CubicSDR-a000446610482299db079a1216774ed05d764165/src/sdr/SDRDeviceInfo.cpp
In file included from /opt/local/var/macports/build/_Users_travis_build_macports_macports-ports_science_CubicSDR/CubicSDR/work/CubicSDR-a000446610482299db079a1216774ed05d764165/src/SessionMgr.cpp:4:
In file included from /opt/local/var/macports/build/_Users_travis_build_macports_macports-ports_science_CubicSDR/CubicSDR/work/CubicSDR-a000446610482299db079a1216774ed05d764165/src/SessionMgr.h:7:
In file included from /opt/local/var/macports/build/_Users_travis_build_macports_macports-ports_science_CubicSDR/CubicSDR/work/CubicSDR-a000446610482299db079a1216774ed05d764165/src/AppFrame.h:6:
In file included from /opt/local/Library/Frameworks/wxWidgets.framework/Versions/wxWidgets/3.1/include/wx-3.1/wx/frame.h:18:
In file included from /opt/local/Library/Frameworks/wxWidgets.framework/Versions/wxWidgets/3.1/include/wx-3.1/wx/toplevel.h:20:
In file included from /opt/local/Library/Frameworks/wxWidgets.framework/Versions/wxWidgets/3.1/include/wx-3.1/wx/nonownedwnd.h:14:
In file included from /opt/local/Library/Frameworks/wxWidgets.framework/Versions/wxWidgets/3.1/include/wx-3.1/wx/window.h:18:
In file included from /opt/local/Library/Frameworks/wxWidgets.framework/Versions/wxWidgets/3.1/include/wx-3.1/wx/event.h:17:
In file included from /opt/local/Library/Frameworks/wxWidgets.framework/Versions/wxWidgets/3.1/include/wx-3.1/wx/clntdata.h:16:
In file included from /opt/local/Library/Frameworks/wxWidgets.framework/Versions/wxWidgets/3.1/include/wx-3.1/wx/hashmap.h:15:
/opt/local/Library/Frameworks/wxWidgets.framework/Versions/wxWidgets/3.1/include/wx-3.1/wx/wxcrt.h:576:14: error: call to 'wcsstr' is ambiguous
    { return wxCRT_StrstrW(haystack, needle); }
             ^~~~~~~~~~~~~
/opt/local/Library/Frameworks/wxWidgets.framework/Versions/wxWidgets/3.1/include/wx-3.1/wx/wxcrtbase.h:119:26: note: expanded from macro 'wxCRT_StrstrW'
#define wxCRT_StrstrW    wcsstr
                         ^~~~~~
/usr/include/wchar.h:141:10: note: candidate function
wchar_t *wcsstr(const wchar_t * __restrict, const wchar_t * __restrict);
         ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cwchar:183:49: note: candidate function
inline _LIBCPP_INLINE_VISIBILITY const wchar_t* wcsstr(const wchar_t* __s1, const wchar_t* __s2) {return ::wcsstr(__s1, __s2);}

error: call to 'wcschr' is ambiguous
error: call to 'wcspbrk' is ambiguous
```
maybe it is related to this commit. Someone suggested in the past to add the macro
```c++
_WCHAR_H_CPLUSPLUS_98_CONFORMANCE_ 
```
but seems not nice. I am not a wxwidgets expert so I am asking you what do you think about the errors? builds fine on macOS 10.13 and 10.14
thank you

macOS 10.12 (darwin/16.7.0) arch i386
MacPorts 2.5.4
Xcode 8.3.3
SDK 10.12
wxWidgets 3.1.2
